folders = ["control", ...
           "devel", ...
           "planning", ...
           "scenario", ...
           "scripts", ...
           "misc", ...
           "tools"];

for folder = folders
    addpath(genpath(folder))
end
