folders = ["control", ...
           "devel", ...
           "planning", ...
           "scenario", ...
           "scripts", ...
           "misc", ...
           "tools", ...
           "analysis", ...
           "vehicle", ...
           "utils"];

for folder = folders
    addpath(genpath(folder))
end
