classdef targetAreaPlot < handle
    properties
       rubberPlot
       linesPlot
    end
    
    methods
        function self = targetAreaPlot()
        end
        
        function plot(self)
            self.obstaclesPlot(3) = plot(polyshape(...
                [-self.params.truckWidth/2 ...
                -self.params.truckWidth/2 ...
                self.params.truckWidth/2 ...
                self.params.truckWidth/2]*1.1, ...
                [-15 -self.params.trailerWheelbase-self.params.trailerMarginBack ...
                -self.params.trailerWheelbase-self.params.trailerMarginBack -15]), ...
                'FaceColor', 'k', ...
                'FaceAlpha', 0.95);
            self.linesPlot(1) = line( ...
                [-self.params.truckWidth/2 -self.params.truckWidth/2]*1.1, ...
                [-self.params.trailerWheelbase-self.params.trailerMarginBack ...
                self.params.truckWheelbase + self.params.truckMargin], ...
                'Color', '#c5c9c9', 'LineWidth', 1.2, 'LineStyle', '-');
            self.linesPlot(2) = line( ...
                [self.params.truckWidth/2 self.params.truckWidth/2]*1.1, ...
                [-self.params.trailerWheelbase-self.params.trailerMarginBack ...
                self.params.truckWheelbase + self.params.truckMargin], ...
                'Color', '#c5c9c9', 'LineWidth', 1.2, 'LineStyle', '-');
        end
    end
end